In [16]:
#Paso 2: Aplicamos Filtro de filas vs columnas 
filtro4= df1.loc[["HELVEX", "DONGA HWASUNG MEXICO"], ["MONTO ADEUDADO"]]
filtro4

                      MONTO ADEUDADO
NOMBRE
HELVEX                      50639.80
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        10759.00
DONGA HWASUNG MEXICO         9396.00

In [17]:
#Filtro por cabecera 
filtro5=df.head()
filtro5

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80

In [18]:
#Filtro por cola
filtro6=df.tail()
filtro6

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

FILTROS BASICOS PARA VARIABLES CUANTITATIVAS

In [19]:
#Filtro por comparacion 
filtro7=df[df["MONTO ADEUDADO"]>70000]
filtro7

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94

FILTROS BASICOS CON CONECTORES LOGICOS

In [20]:
#Filtro Y
filtro8=df[(df["MONTO ADEUDADO"]<6000)&(df["FECHA_FACTURA"]=="2023-03-14")]
filtro8

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
85,409,CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS IN...,F40359,2023-03-14,2023-03-14,4292.00
96,3926,PRODUCTOS PENNSYLVANIA,F40358,2023-03-14,2023-04-13,3368.64
100,3926,PRODUCTOS PENNSYLVANIA,F40357,2023-03-14,2023-04-13,2756.16
101,5926,PÚBLICO EN GENERAL,F40362,2023-03-14,2023-03-14,2694.95
113,2216,FRESCOPACK,F40355,2023-03-14,2023-03-14,1682.00
132,1284,TERMOFORMADOS,F40349,2023-03-14,2023-04-13,799.24
135,8872,GABRIELA GARCIA SANCHEZ,F40360,2023-03-14,2023-03-14,754.00
139,8228,UCH COMERCIAL,F40365,2023-03-14,2023-03-14,702.96

In [26]:
#Filtro 0, una u otra o las dos
filtro9=df[(df["MONTO ADEUDADO"]<6000) | (df["FECHA_FACTURA"]=="2023-03-14")]
filtro9

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
9,644,CLAVOS NACIONALES C.N,F40351,2023-03-14,2023-05-13,45216.34
10,3937,RICHALUM,F40361,2023-03-14,2023-03-14,42880.05
36,417,COVEMEX,F40354,2023-03-14,2023-03-29,15843.28
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [23]:
#Filtro not
filtro10=df[~(df["FECHA_FACTURA"]=="2023-03-14")]
filtro10

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80
5,1429,AUTOLIV STEERING WHEELS MEXICO,F39979,2023-01-24,2023-03-25,49416.00
6,1429,AUTOLIV STEERING WHEELS MEXICO,F40319,2023-03-08,2023-05-07,49416.00
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [24]:
#Convertir archivos filtrado a CSV
filtro10.to_csv("Entregable1.csv")

In [15]:
df1= pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx', index_col=1)
df1

,No. CLIENTE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
NOMBRE,,,,,
DONGA HWASUNG MEXICO,6401,F40238,2023-02-24,2023-03-26,97485.94
DONGA HWASUNG MEXICO,6401,F40353,2023-03-14,2023-04-13,97485.94
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,4598,F40352,2023-03-14,2023-04-13,64916.21
INDUSTRIAS LANCERMEX,3930,F40217,2023-02-23,2023-03-25,52715.74
HELVEX,4712,F40173,2023-02-17,2023-04-03,50639.80
...,...,...,...,...,...
CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL,856,F40055,2023-01-31,2023-01-31,56.00
PÚBLICO EN GENERAL,5926,NV00777,2023-03-07,2023-03-07,45.00
PÚBLICO EN GENERAL,5926,NV00778,2023-03-09,2023-03-09,40.00
PÚBLICO EN GENERAL,5926,NV00779,2023-03-09,2023-03-09,24.01
FISHERS QUERETARO,8429,F38248,2022-05-27,2022-05-27,19.94

In [14]:
#Filtro por columnas 
#filtro3= df.iloc[:, 1:3]   #Columnas consecutivas
filtro3= df.iloc[:, [1,4,5]]    #Columnas no consecutivas
filtro3

,NOMBRE,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,DONGA HWASUNG MEXICO,2023-03-26,97485.94
1,DONGA HWASUNG MEXICO,2023-04-13,97485.94
2,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,2023-04-13,64916.21
3,INDUSTRIAS LANCERMEX,2023-03-25,52715.74
4,HELVEX,2023-04-03,50639.80
...,...,...,...
159,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,2023-01-31,56.00
160,PÚBLICO EN GENERAL,2023-03-07,45.00
161,PÚBLICO EN GENERAL,2023-03-09,40.00
162,PÚBLICO EN GENERAL,2023-03-09,24.01
163,FISHERS QUERETARO,2022-05-27,19.94

In [11]:
#Filtro por filas 
filtro2= df.iloc[3:10,: ]   #Filas consecutivas
#filtro2= df.iloc[[2,5], :]     #Filas no consecutivas
filtro2

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80
5,1429,AUTOLIV STEERING WHEELS MEXICO,F39979,2023-01-24,2023-03-25,49416.00
6,1429,AUTOLIV STEERING WHEELS MEXICO,F40319,2023-03-08,2023-05-07,49416.00
7,5039,BUSSMANN,F40082,2023-02-04,2023-02-04,48882.12
8,644,CLAVOS NACIONALES C.N,F40340,2023-03-13,2023-05-12,45216.34
9,644,CLAVOS NACIONALES C.N,F40351,2023-03-14,2023-05-13,45216.34

In [9]:
#Filtros basicos 
#Filtro por objeto 
filtro1=df[(df["NOMBRE"]== "INDUSTRIAS LANCERMEX")]
filtro1

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
12,3930,INDUSTRIAS LANCERMEX,F40114,2023-02-09,2023-03-11,35143.82

In [8]:
#Verificamos informacion del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   No. CLIENTE        162 non-null    object
 1   NOMBRE             163 non-null    object
 2   FACTURA            163 non-null    object
 3   FECHA_FACTURA      163 non-null    datetime64[ns]
 4   FECHA_VENCIMIENTO  164 non-null    datetime64[ns]
 5   MONTO ADEUDADO     163 non-null    float64
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 7.8+ KB

In [6]:
df= pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx')
df
#Df, al ejecutar se muestra nuestra db

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [ ]:
#Importacion de librerias
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns